id: P003147
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137887
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་བརྒྱད་པ་བློ་བཟང་བསྟན་པའི་དབང་ཕྱུག་འཇམ་དཔལ་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  volumes:
    24ddac002a864e9685cfa9134459553c:
      image_group_id: I2PD17665
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
