id: I788C792C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:25:40+00:00'
last_modified: '2022-06-07T17:54:40.668156+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137887
  title: རྒྱལ་དབང་སྐུ་ཕྲེང་བརྒྱད་པ་བློ་བཟང་བསྟན་པའི་དབང་ཕྱུག་འཇམ་དཔལ་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    16C0:
      image_group_id: I2PD17665
      title: ''
      total_pages: 602
      order: 1
      base_file: 16C0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
